# Generated by Django 3.0.8 on 2020-08-03 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TText',
            fields=[
                ('idtext', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=45)),
                ('author', models.CharField(max_length=45)),
                ('source', models.CharField(max_length=150)),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'TText',
            },
        ),
    ]
