# Generated by Django 3.0.7 on 2020-06-29 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TUser',
            fields=[
                ('iduser', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=45)),
                ('password', models.CharField(max_length=45)),
                ('security_question', models.CharField(max_length=100)),
                ('security_answer', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'TUser',
            },
        ),
    ]
